### ISSUE TITLE
In order to choose a permit, as an applicant who knows I need a permit, but not which type, I need to be guided to the appropriate permit application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#36]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed
