### ISSUE TITLE
In order to understand permit needs and potentially choose a permit, as a user less familiar with Forest Service offerings, I want to learn if what I want to do requires a permit, and if it does I need to be guided to the correct permit application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#37]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Visual design review passed
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed

**Comment by dubharmonic** [comment]
Closed because we've completed the find a permit wizard.
