### ISSUE TITLE
In order to access a permit that isn’t offered by the US Forest Service online, as a user I want instructions that tell me where to go to get my permit and how to submit it. (links to existing site)

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#39]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Visual design review passed
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed

**Comment by dubharmonic** [comment]
Duplicate of #38
