### ISSUE TITLE
In order to begin completing an application, as an outfitter or guide, I would like to jump immediately to the temp outfitter permit application.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#40]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Visual design review passed
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed
