### ISSUE TITLE
As a Forest Service special uses administrator, I would like to be able to accept an application and send a request to the API to enter that information into SUDS.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#84]
Definition of Done
- [ ] Acceptance criteria met (UAT)
- [ ] Code refactored for clarity
- [ ] Framework code decoupled from ours
- [ ] Source code committed
- [ ] Unit test coverage of our code = 100%
- [ ] Code reviewed (or developed by pair)
- [ ] Security reviewed and reported
- [ ] No local design debt
- [ ] Build process updated
- [ ] Source documentation generated
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Guides and training draft updated
- [ ] Security & privacy gates passed
